[env]
TERM = "xterm-256color"

[window]
opacity = 0.83
blur = true

[font]
size = 11.0
normal = { family = "FiraCode Nerd Font" }

[colors]
[colors.primary]
background = '#111217'
foreground = '#F2F2F2'

[colors.normal]
black   = "#1F2229"
red     = "#D41919"
green   = "#5EBDAB"
yellow  = "#FF9632"
blue    = "#2452A12"
magenta = "#9755B3"
cyan    = "#BCB6FF"
white   = "#E6E6E6"

[colors.bright]
black   = "#198388"
red     = "#EC0101"
green   = "#2CA84E"
yellow  = "#F9F1A5"
blue    = "#277FFF"
magenta = "#962AC3"
cyan    = "#05A1F7"
white   = "#F2F2F2"

[colors.cursor]
text   = "#000000"
cursor = "#FFFFFF"
